name: .NET 5

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET CLI
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.4.20258.7
    - name: Install dependencies
      run: dotnet restore ./src/
    - name: Build
      run: dotnet build --configuration Release --no-restore --nologo ./src/
    - name: Test
      run: dotnet test --no-restore --verbosity normal --nologo ./src/
